CREATE DATABASE IF NOT EXISTS ASSIGNMENT3;
USE ASSIGNMENT4;
CREATE TABLE shopkeepers(
income INT ,
NAME VARCHAR(50),
ID_NUMBER INT PRIMARY KEY);

INSERT INTO shopkeepers VALUES(34500,"ADEEB",34343);
INSERT INTO  shopkeepers VALUES(100000,"MEHRAN",34344);
CREATE TABLE CUSTOMERS(INCOME INT,NAME VARCHAR(50));
INSERT INTO CUSTOMERS VALUES(345000,"ABCE");
INSERT INTO CUSTOMERS VALUES(345050,"ABCEFGJ");
DROP TABLE CUSTOMERS;
TRUNCATE TABLE SHOPKEEPERS;
